// Mock data for demo mode (no API key required).
// Edit candidates, conversations, and parsedJD here to customize the demo.

export const MOCK_PARSED_JD = {
  role_title: "Senior Full Stack Engineer",
  company: "Finvo",
  exp_years_min: 5,
  required_skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "AWS"],
  nice_to_have: ["FinTech domain knowledge", "GraphQL", "tRPC", "Open-source contributions", "Mentoring junior engineers"],
  seniority: "senior",
  domain: "FinTech / Payments",
};

export const MOCK_CANDIDATES = [
  {
    id: "c1",
    name: "Maya Patel",
    current_title: "Senior Full Stack Engineer",
    current_company: "Stripe",
    years_exp: 7,
    location: "New York, USA",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "AWS", "GraphQL", "Payments APIs", "Docker", "tRPC"],
    education: "B.S. Computer Science, Carnegie Mellon University",
    match_score: 93,
    match_reasons: [
      "7 years full-stack experience with React + TypeScript as daily drivers",
      "Deep payments domain knowledge from 3 years at Stripe processing high-volume transactions",
      "Expert in PostgreSQL and Redis — led database performance initiative cutting query latency by 40%",
      "AWS certified (ECS, RDS, Lambda) with hands-on production experience",
    ],
    gaps: ["No open-source contributions found"],
    bio: "Senior engineer at Stripe building payment orchestration systems that handle millions of transactions daily. Passionate about developer tooling and performance engineering at scale.",
  },
  {
    id: "c2",
    name: "Alex Chen",
    current_title: "Staff Software Engineer",
    current_company: "Plaid",
    years_exp: 8,
    location: "San Francisco, USA",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Redis", "AWS", "Python", "Kafka", "tRPC", "GraphQL"],
    education: "M.S. Computer Science, Stanford University",
    match_score: 88,
    match_reasons: [
      "8 years of full-stack experience, most recently as Staff Engineer at Plaid (FinTech)",
      "Owns end-to-end features in a regulated financial data environment — mirrors Finvo's context",
      "Strong Python background (a listed nice-to-have) alongside Node.js",
      "Active open-source contributor with 2 popular npm packages (combined 50k weekly downloads)",
    ],
    gaps: ["Staff-level candidate may find IC scope at a 5-person team limiting"],
    bio: "Staff engineer at Plaid specializing in financial data infrastructure and developer APIs. Author of two widely-used open-source libraries for financial data normalization.",
  },
  {
    id: "c3",
    name: "Jordan Williams",
    current_title: "Senior Software Engineer",
    current_company: "Square (Block)",
    years_exp: 6,
    location: "Remote (EST)",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "Python", "Redis", "Docker", "Mentoring"],
    education: "B.S. Software Engineering, Georgia Tech",
    match_score: 82,
    match_reasons: [
      "6 years full-stack with React/TypeScript and Node.js matching core requirements exactly",
      "Experience shipping payment features at Square (Cash App) — strong domain relevance",
      "Mentored 3 junior engineers and ran weekly tech talks — satisfies the mentoring nice-to-have",
      "AWS experience across ECS and Lambda in production",
    ],
    gaps: ["Redis experience is limited to caching — no pub/sub or stream usage"],
    bio: "Software engineer at Square building merchant-facing payment flows. Enjoys mentoring early-career engineers and is an organizer of a regional React meetup.",
  },
  {
    id: "c4",
    name: "Priya Sharma",
    current_title: "Full Stack Developer",
    current_company: "Shopify",
    years_exp: 5,
    location: "Toronto, Canada",
    skills: ["React", "TypeScript", "Ruby on Rails", "PostgreSQL", "Redis", "Google Cloud", "GraphQL"],
    education: "B.Eng. Computer Engineering, University of Waterloo",
    match_score: 71,
    match_reasons: [
      "5 years experience meeting the minimum requirement",
      "Strong React and TypeScript skills from Shopify's frontend-heavy stack",
      "PostgreSQL and GraphQL experience align well with the role",
    ],
    gaps: [
      "Node.js experience is minimal — primary backend is Ruby on Rails",
      "AWS experience is absent — Shopify runs on Google Cloud",
      "No FinTech or payments domain background",
    ],
    bio: "Full stack developer at Shopify building merchant analytics dashboards. Strong in React and data visualization, currently expanding backend skills.",
  },
  {
    id: "c5",
    name: "Marcus Thompson",
    current_title: "Backend Engineer",
    current_company: "Twilio",
    years_exp: 6,
    location: "Austin, USA",
    skills: ["Node.js", "Python", "PostgreSQL", "Redis", "AWS", "Kafka", "Docker", "Kubernetes"],
    education: "B.S. Computer Science, UT Austin",
    match_score: 64,
    match_reasons: [
      "Strong Node.js and AWS expertise matches backend requirements",
      "6 years of experience at high-growth startup (Twilio)",
      "Deep PostgreSQL and Redis knowledge including cluster management",
    ],
    gaps: [
      "Frontend skills are very limited — rarely writes React or TypeScript",
      "No FinTech domain experience",
      "Not a full-stack profile — primarily backend/infra focused",
    ],
    bio: "Backend engineer at Twilio focused on messaging infrastructure and API reliability. Enjoys distributed systems problems and has a strong DevOps background.",
  },
  {
    id: "c6",
    name: "Yuki Tanaka",
    current_title: "Frontend Lead",
    current_company: "Figma",
    years_exp: 7,
    location: "Seattle, USA",
    skills: ["React", "TypeScript", "JavaScript", "CSS", "WebGL", "Performance optimization", "Design systems"],
    education: "B.S. Human-Computer Interaction, University of Washington",
    match_score: 57,
    match_reasons: [
      "World-class React and TypeScript skills — builds complex interactive UIs",
      "7 years experience at high-growth tech companies",
    ],
    gaps: [
      "No backend experience — Node.js, PostgreSQL, Redis, AWS all absent from profile",
      "Product design tool background has no overlap with FinTech/payments domain",
      "Not a full-stack candidate — firmly a frontend specialist",
    ],
    bio: "Frontend lead at Figma working on the canvas rendering engine and design system. Expert in React performance and has given talks at React Summit and JSConf.",
  },
  {
    id: "c7",
    name: "Sam Rodriguez",
    current_title: "Software Engineer II",
    current_company: "Netflix",
    years_exp: 4,
    location: "Los Angeles, USA",
    skills: ["React", "TypeScript", "Java", "MySQL", "AWS", "Spring Boot"],
    education: "B.S. Computer Science, UCLA",
    match_score: 43,
    match_reasons: [
      "React and TypeScript experience is relevant for the frontend layer",
      "AWS familiarity from Netflix infrastructure",
    ],
    gaps: [
      "4 years experience falls below the 5-year minimum",
      "Backend is Java/Spring Boot — no Node.js experience",
      "No Redis experience",
      "Consumer media background is far from FinTech/payments",
    ],
    bio: "Software engineer at Netflix working on the member-facing growth team. Primarily builds A/B test frameworks and onboarding flows.",
  },
  {
    id: "c8",
    name: "Chris Lee",
    current_title: "Junior Full Stack Developer",
    current_company: "Accenture Federal",
    years_exp: 2,
    location: "Washington D.C., USA",
    skills: ["React", "JavaScript", "Node.js", "MySQL", "Azure"],
    education: "B.S. Information Systems, George Mason University",
    match_score: 31,
    match_reasons: [
      "Some React and Node.js exposure is relevant",
    ],
    gaps: [
      "2 years experience — significantly below 5-year minimum",
      "No TypeScript, PostgreSQL, Redis, or AWS",
      "Consulting/government background with no startup or FinTech experience",
      "Junior-level seniority doesn't match senior role scope",
    ],
    bio: "Junior developer at Accenture Federal building internal tooling for government clients. Recently completed AWS Cloud Practitioner certification and eager to transition to product companies.",
  },
];

export const MOCK_CONVERSATIONS = {
  c1: {
    conversation: [
      { role: "recruiter", msg: "Hi Maya! I came across your profile and was genuinely impressed by your payments work at Stripe. We're building B2B payment rails at Finvo — Series B, processing $3B annually with a tight-knit team of 5 engineers. We're looking for a senior full-stack engineer to own features end-to-end. Would love to share more if you're open to it!" },
      { role: "candidate", msg: "Thanks for reaching out! Finvo sounds interesting — I'm familiar with the B2B rails space from my time on Stripe's API infrastructure team. A few questions: what does the stack look like, and how much ownership does an individual engineer get over product decisions? I'm currently happy at Stripe but am open to conversations for the right opportunity." },
      { role: "recruiter", msg: "Great questions! The stack is React + TypeScript frontend, Node.js backend, PostgreSQL + Redis, deployed on AWS (ECS + Lambda). Every engineer owns their domain completely — no PMs, engineers write the specs. The CTO is technical and loves deep technical debates. Comp is $160–200k + meaningful equity at a Series B valuation we think is very attractive." },
      { role: "candidate", msg: "That stack is basically identical to what I use daily, which is reassuring. The ownership model and CTO dynamic sound appealing — I've been missing that at Stripe where things are getting more process-heavy. I'd be open to a 30-minute call to learn more about the product roadmap and team culture. Can we find time next week?" },
    ],
    interest_score: 82,
    interest_signals: ["Asked sharp technical questions", "Familiar with the problem space", "Proactively proposed next step"],
    concerns: ["Currently happy at Stripe — may require competitive offer"],
    availability: "3–4 weeks notice",
  },
  c2: {
    conversation: [
      { role: "recruiter", msg: "Hi Alex! Your open-source work on financial data normalization caught my eye — really impressive stuff. At Finvo we're building next-gen B2B payment rails processing $3B/year. We're a Series B team of 5 engineers and are looking for someone senior to help us scale. Your Plaid background makes you a strong potential fit — would you be interested in learning more?" },
      { role: "candidate", msg: "Hey! Thanks for the kind words on the OSS work. Plaid has been a great run but I've been thinking about going somewhere where I can have more direct product impact — Staff at a large company is still lots of coordination overhead. The $3B payment volume and small team dynamic is interesting. What's the founding story and what does the technical roadmap look like for the next 12 months?" },
      { role: "recruiter", msg: "Founded in 2021 by ex-Brex and Marqeta engineers. The next 12 months are all about expanding from ACH/wire rails to real-time payment networks (RTP, FedNow), plus building the developer platform layer. It's a genuinely hard technical problem. Stack is React/TypeScript/Node/PostgreSQL/Redis/AWS. Comp is $160–200k + equity." },
      { role: "candidate", msg: "RTP and FedNow expansion is exactly the kind of meaty infrastructure problem I'd want to sink my teeth into. I've been adjacent to that space at Plaid but never owned it directly. I'd definitely want to talk to the CTO to understand the architecture decisions made so far and where the hard problems are. Happy to schedule something — what's availability like on your end?" },
    ],
    interest_score: 88,
    interest_signals: ["Asked about technical roadmap depth", "Self-identified motivation for change", "Requested CTO conversation — high engagement signal"],
    concerns: ["Staff → Senior title may be a concern for ego/leveling"],
    availability: "4 weeks notice",
  },
  c3: {
    conversation: [
      { role: "recruiter", msg: "Hi Jordan! I noticed your full-stack work at Square and your mentorship involvement — both really stood out. Finvo is a Series B FinTech building B2B payment rails, and we're hiring a senior full-stack engineer to join a team of 5. Your payments background and engineering culture interests seem like a strong match. Would you be open to a conversation?" },
      { role: "candidate", msg: "Hi! Thanks for reaching out — Finvo sounds familiar, I think I saw some coverage of your Series B. I'm fairly happy at Square but I'm open to hearing about what you're building. Remote-friendly? And what's the team composition — mostly IC engineers or a lot of eng management overhead?" },
      { role: "recruiter", msg: "Fully remote-first with quarterly offsites. The team is 4 ICs + 1 CTO, no middle management at all. Everyone contributes to architecture decisions. Stack is React/TypeScript/Node.js/PostgreSQL/Redis on AWS. Comp range is $160–200k + equity. Given your Square experience with payment flows, we think you'd be owning meaningful features from day one." },
      { role: "candidate", msg: "The team structure and remote setup sound great. I've been wanting something with less process overhead than Square has developed over the past couple years. I'd be interested in a call — mostly want to understand what 'end-to-end ownership' really means in practice and what the oncall story looks like. Can we do something next week?" },
    ],
    interest_score: 76,
    interest_signals: ["Remote setup is a positive", "Motivated by less process overhead", "Requested call with specific questions"],
    concerns: ["Oncall concerns could be a friction point"],
    availability: "2 weeks notice",
  },
  c4: {
    conversation: [
      { role: "recruiter", msg: "Hi Priya! Your full-stack work at Shopify and strong React/TypeScript background caught our attention. Finvo is a Series B FinTech building B2B payment rails and we're growing our engineering team. We think your frontend skills could translate well — would you be open to learning more?" },
      { role: "candidate", msg: "Hi, thanks for reaching out! I've been curious about FinTech for a while — the domain seems interesting. I should be upfront that my backend experience is mostly Ruby on Rails, not Node.js, and I don't have much AWS experience (we use GCP at Shopify). Would those be hard blockers for the role?" },
      { role: "recruiter", msg: "Good question — Node.js is definitely a core skill we're hiring for, but engineers who are strong in one backend and motivated to learn have done well on our team before. The fundamentals transfer. We'd probably assess your backend depth during interviews and see how quickly you can ramp. The React/TypeScript side would be immediately valuable. The comp range is $160–200k." },
      { role: "candidate", msg: "I appreciate the transparency. I'm genuinely interested in the problem space and the startup size sounds appealing compared to Shopify's scale. I'd need to be honest that I'd be ramping on Node.js and AWS on the job — if the team is okay with that trajectory, I'd be open to talking more. What does the interview process look like?" },
    ],
    interest_score: 63,
    interest_signals: ["Genuine interest in FinTech domain", "Transparent about skill gaps — intellectual honesty"],
    concerns: ["Self-identified Node.js and AWS gaps", "May require longer ramp time than other candidates"],
    availability: "3 weeks notice",
  },
  c5: {
    conversation: [
      { role: "recruiter", msg: "Hi Marcus! Your backend infrastructure work at Twilio is really impressive — deep Node.js and AWS expertise is exactly what we look for. Finvo is a Series B FinTech building high-reliability payment rails and we're expanding the team. Would you be interested in hearing more?" },
      { role: "candidate", msg: "Thanks! Twilio has been good but I've been thinking about a change. One thing I want to flag upfront — I'm primarily a backend/infra engineer. My React skills are honestly pretty basic, maybe a month of professional experience total. Is this role truly full-stack or could it flex toward backend-heavy?" },
      { role: "recruiter", msg: "Honest answer — the role does require meaningful frontend contributions. We're a small team and everyone ships from API to UI. That said, if your backend depth is strong enough, some engineers on our team have leaned backend-heavy in practice. The JD says full-stack but the needs vary. It would depend on what the team needs at the time you join." },
      { role: "candidate", msg: "I appreciate the honesty. I'm a bit hesitant to commit to a role that could pull me heavily into React work — it's not where I want to grow. If there's a clear backend-focused opening or if the frontend piece becomes more optional, I'd revisit. For now, I think it might not be the right fit, but I'm open to staying in touch." },
    ],
    interest_score: 38,
    interest_signals: ["Strong backend motivation", "Appreciated transparency from recruiter"],
    concerns: ["Explicitly not interested in frontend work", "Self-selected out during conversation"],
    availability: "Could start in 4 weeks if interested",
  },
  c6: {
    conversation: [
      { role: "recruiter", msg: "Hi Yuki! Your React performance work at Figma is genuinely impressive — you clearly have deep frontend expertise. Finvo is building B2B payment rails and we're looking for a senior full-stack engineer. Your frontend skills would be incredibly valuable. Would you be open to a conversation?" },
      { role: "candidate", msg: "Hi! Thanks for reaching out. I should be straightforward — I'm pretty firmly a frontend engineer. I don't write backend code professionally and I don't have database or AWS experience. If the role requires full-stack contributions, I'm probably not the right fit. What does the frontend-backend split look like on a day-to-day basis?" },
      { role: "recruiter", msg: "Appreciate the candor! The role is genuinely full-stack — engineers own features from DB schema to UI. That said, your React performance expertise is at a level we rarely see in candidates, so I wanted to explore. Would there be any interest in a frontend-specialized role if one opened up, or is the FinTech domain not interesting to you?" },
      { role: "candidate", msg: "FinTech isn't really in my wheelhouse and I'd feel out of my depth on the backend requirements you're describing. I'd recommend focusing on candidates with full-stack backgrounds for this one. If Figma ever opens a role or if you have frontend-only opportunities in the future, feel free to reach out. Appreciate you taking the time!" },
      ],
    interest_score: 22,
    interest_signals: [],
    concerns: ["Politely declined — not a full-stack candidate", "No FinTech interest"],
    availability: "Not applicable",
  },
};
